version: '3'

services:

  # PostgreSQL, backend ,expose 5432
  app-postgres:
    image: arm32v7/postgres
    container_name: app-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    networks:
      - backend
    expose:
      - "5432"
    # volumes:
    #   - ./config/postgresql:/etc/postgresql:ro

  # Redis, backend, expose 6379
  app-redis:
    image: arm32v7/redis
    container_name: app-redis
    networks:
      - backend
    expose:
      - "6379"
    # volumes:
    #   - ./config/redis:/etc/redis:ro

  # KBS, frontend & backend, expose 8080 - 8082
  app-server:
    build: ./server
    container_name: app-server
    depends_on:
      - app-postgres
      - app-redis
    links:
      - app-postgres
      - app-redis
    networks:
      - frontend
      - backend
    expose:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - ./client:/app/client:ro

  # Nginx, frontend & backend & hostnet, ports 80 & 443 & 13306(dev) & 16379(dev)
  app-nginx:
    image: arm32v7/nginx
    container_name: app-nginx
    depends_on:
      - app-server
    links:
      - app-postgres
      - app-redis
      - app-server
    networks:
      - frontend
      - backend
      - hostnet
    ports:
      - "80:80"
      - "443:443"
      # - "13306:3306"
      - "15432:5432"
      - "16379:6379"
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./client:/app:ro

networks:
  frontend:
  backend:
  hostnet:
    external: true
